# Generated by Django 5.2.7 on 2025-10-05 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField()),
                ('comuna', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('contacto_principal', models.CharField(blank=True, max_length=100)),
                ('plazo_entrega_dias', models.PositiveIntegerField(default=7)),
                ('condiciones_pago', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlertaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('stock_critico', 'Stock Crítico'), ('sin_stock', 'Sin Stock'), ('vencimiento', 'Vencimiento Próximo'), ('movimiento_anomalo', 'Movimiento Anómalo')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
                'ordering': ['-fecha_alerta'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('fecha_esperada', models.DateField()),
                ('fecha_recibida', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ordenada', 'Ordenada'), ('parcialmente_recibida', 'Parcialmente Recibida'), ('recibida', 'Recibida'), ('facturada', 'Facturada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=25)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('notas_internas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferencia'), ('devolucion', 'Devolución')], max_length=20)),
                ('motivo_entrada', models.CharField(blank=True, choices=[('compra', 'Compra'), ('devolucion_cliente', 'Devolución de Cliente'), ('ajuste_inventario', 'Ajuste de Inventario'), ('transferencia_entrada', 'Transferencia Entrada'), ('inventario_inicial', 'Inventario Inicial')], max_length=30)),
                ('motivo_salida', models.CharField(blank=True, choices=[('venta', 'Venta'), ('devolucion_proveedor', 'Devolución a Proveedor'), ('ajuste_inventario', 'Ajuste de Inventario'), ('transferencia_salida', 'Transferencia Salida'), ('perdida', 'Pérdida/Deterioro'), ('muestra', 'Muestra')], max_length=30)),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_anterior', models.PositiveIntegerField()),
                ('cantidad_nueva', models.PositiveIntegerField()),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'unique_together': {('compra', 'producto')},
            },
        ),
    ]
