# Generated by Django 5.2.7 on 2025-10-21 22:25

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_imagen_cotizacion_detallecotizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('mercadopago', 'MercadoPago'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TransferenciaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Verificación'), ('verificando', 'En Verificación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='pendiente', max_length=20)),
                ('banco_destino', models.CharField(default='Banco DuocUC', max_length=100)),
                ('tipo_cuenta', models.CharField(default='Cuenta Corriente', max_length=50)),
                ('numero_cuenta', models.CharField(default='12.345.678-9', max_length=20)),
                ('nombre_titular', models.CharField(default='Duoc UC', max_length=200)),
                ('monto_transferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_transferencia', models.DateTimeField(blank=True, null=True)),
                ('numero_transaccion', models.CharField(blank=True, help_text='Número de transacción bancaria', max_length=50)),
                ('comprobante', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='comprobantes/')),
                ('observaciones_cliente', models.TextField(blank=True, help_text='Observaciones del cliente')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_verificador', models.TextField(blank=True, help_text='Observaciones del verificador')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha límite para realizar la transferencia')),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia', to='tienda.cotizacion')),
                ('verificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_verificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia Bancaria',
                'verbose_name_plural': 'Transferencias Bancarias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
