# Generated by Django 5.2.7 on 2025-11-14 01:28

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_cotizacion_metodo_pago_transferenciabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='comentarios_pago',
            field=models.TextField(blank=True, help_text='Comentarios adicionales sobre el pago'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='comprobante_pago',
            field=models.FileField(blank=True, help_text='Comprobante de transferencia bancaria', null=True, storage=storages.backends.s3.S3Storage(), upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('finalizada', 'Finalizada'), ('en_revision', 'En Revisión'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
    ]
