# Generated by Django 5.2.7 on 2025-10-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_email_verificado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Código de Verificación de Email', 'verbose_name_plural': 'Códigos de Verificación de Email'},
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='codigo',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='intentos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
