# Generated by Django 5.2.7 on 2025-10-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_emailverificationtoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='api_token',
            field=models.CharField(blank=True, help_text='Token de 6 dígitos para chatbot', max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
